In [1]:
from sklearn import preprocessing
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.svm import SVC
import matplotlib.pyplot as plt

In [2]:
a = np.array([
    [10, 2.7,3.6],
    [-100, 5, -2],
    [120, 20, 40]
], dtype=np.float64)
print(a)
print(preprocessing.scale(a))

[[  10.     2.7    3.6]
 [-100.     5.    -2. ]
 [ 120.    20.    40. ]]
[[ 0.         -0.85170713 -0.55138018]
 [-1.22474487 -0.55187146 -0.852133  ]
 [ 1.22474487  1.40357859  1.40351318]]


In [165]:
data_X, data_Y = make_classification(n_samples = 300, n_features = 6, n_redundant = 2, n_informative = 4, 
                                     random_state = None, n_clusters_per_class = 2, scale = 100)
scaler = preprocessing.StandardScaler().fit(data_X)
X_train, X_test, Y_train, Y_test = train_test_split(data_X, data_Y, test_size = 0.3)

In [166]:
#plt.scatter(data_X[:, 0], data_X[:, 1], c=data_Y)
#plt.show()
clf = SVC()
clf.fit(X_train, Y_train)
print(clf.score(X_test, Y_test))

0.8444444444444444


In [167]:
X_train_scaler = scaler.transform(X_train)
X_test_scaler = scaler.transform(X_test)
clf2 = SVC()
clf2.fit(X_train_scaler, Y_train)
print(clf2.score(X_test_scaler, Y_test))

0.8666666666666667
